/* tslint:disable */
/* eslint-disable */
/**
 * WODSS Gruppe 02 Backend API
 * API for WODSS Gruppe 02 Backend
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

