# This is a basic workflow to help you get started with Actions

name: Deploy to switch engine

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          
      - name: Change Directory
        run: cd corona-navigator
        
      - name: Install NPM Packages
        run: npm install
        
      - name: build react app
        run: npm run build
      
      
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@9ab39935552e9fe6706e9c9bf2a70a3328a4a5e6
        uses: easingthemes/ssh-deploy@v2
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Remote port
          # REMOTE_PORT: # optional, default is 22
          # Source directory
          SOURCE: 'build/'
          # Target directory
          TARGET: '/var/www/html/corona-navigator/' # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          # ARGS: # optional, default is -rltgoDzvO
          # An array of folder to exclude
          EXCLUDE: '/dist/, /node_modules/' # optional, default is 
      - name: Success Message
        run: |
          echo "=========\033[;32mSuccess\033[0m========="
          echo "Build and deployment run successfuly"
          echo "========Tschüssli========"
